version: '3.8'
services:
  users-service:
    build: ./services/users
    ports:
      - "8080:8080"
    networks:
      - microservices-net

  orders-service:
    build: ./services/orders
    ports:
      - "8081:8081"
    networks:
      - microservices-net

  products-service:
    build: ./services/products
    ports:
      - "8082:8082"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
